modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/astryxion23/Mob-Dismemberment/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/astryxion23/Mob-Dismemberment"
authors = "${mod_authors}"
description = '''
Dismember mobs! When zombies, skeletons, and creepers die, they fall apart into pieces.

Credits: ${mod_credits}
'''

[[dependencies.mobdismemberment]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobdismemberment]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
