modLoader="javafml"
loaderVersion="[36,)"
license="${mod_license}"
issueTrackerURL="https://github.com/astryxion23/Mob-Dismemberment/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/astryxion23/Mob-Dismemberment"
authors="${mod_authors}"
description='''
Dismember mobs! When zombies, skeletons, and creepers die, they fall apart into pieces.
Client-side only - safe to omit from dedicated servers (install on clients for the effect).

Credits: ${mod_credits}
'''

[[dependencies.mobdismemberment]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="CLIENT"

[[dependencies.mobdismemberment]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="CLIENT"
